# Written by Kenvix @ 2016/7/13
# Variables
code="" #QucikLogin Code.Generated By MoeCraft
echo -e "\033[31;49;1mMoeCraft Quick Login // 作者：Kenvix [ http://kenvix.com ]\e[0m"
if [ ! -n ${code} ]; then
    echo -e "\033[32;49;1m错误：找不到密钥，请前往 用户中心->两步验证 重新生成shell\e[0m"
else
    echo -e "\033[32;49;1m正在获取本机网址...\e[0m"
    ip=`curl http://members.3322.org/dyndns/getip`
    if [ ! -n ${ip} ]; then
        echo -e "\033[32;49;1m错误：获取不到本机外网IP地址，请重试\e[0m"
    else
        echo -e "\033[32;49;1m获取到本机IP地址为：${ip}\e[0m"
        echo -e "\033[32;49;1m正在准备快捷登录...\e[0m"
        result=`curl -d "ip=${ip}&code=${code}" "https://accounts.moecraft.net/index.php?m=home&c=mc&a=gameLoginAPI"`
        echo -e "\033[32;49;1m${result}\e[0m"
    fi
fi 