//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoecraftPkgInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoecraftPkgInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Registry Editor Version 5.00
        ///
        ///[HKEY_CLASSES_ROOT\.moecraftpkg]
        ///@=&quot;MoecraftUpdater.Pkg&quot;
        ///
        ///[HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg]
        ///@=&quot;MoeCraft Package File&quot;
        ///
        ///[HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg\shell]
        ///
        ///[HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg\shell\DefaultIcon]
        ///@=&quot;{selfpath}&quot;
        ///
        ///[HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg\shell\open]
        ///@=&quot;安装 (&amp;I)&quot;
        ///&quot;Icon&quot;=&quot;{selfpath}&quot;
        ///
        ///[HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg\shell\open\command]
        ///@=&quot;\&quot;{selfpath}\&quot; \&quot;%1\&quot;&quot; 的本地化字符串。
        /// </summary>
        internal static string setass {
            get {
                return ResourceManager.GetString("setass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows Registry Editor Version 5.00
        ///
        ///[-HKEY_CLASSES_ROOT\.moecraftpkg]
        ///[-HKEY_CLASSES_ROOT\MoecraftUpdater.Pkg] 的本地化字符串。
        /// </summary>
        internal static string unsetass {
            get {
                return ResourceManager.GetString("unsetass", resourceCulture);
            }
        }
    }
}
